### ISSUE TITLE
Upload both 32/64bit binaries to GH releases

### ISSUE THREAD

**Issue by StefanScherer** [pecigonzalo/docker-machine-vmwareworkstation#2]
At the moment both 32bit and 64bit windows exefiles have the same name and so they will be overwritten in the github release step.

We should name the plugins like docker-machine itself https://github.com/docker/machine/releases
- docker-machine-driver-vmwareworkstation_windows-386.exe
- docker-machine-driver-vmwareworkstation_windows-amd64.exe

Proposal to update the `appveyor.yml`:

``` yaml
  - go build -i -o ./bin/docker-machine-driver-vmwareworkstation_windows-%GOARCH%.exe ./cmd/

# Deploy
artifacts:
  - path: bin/docker-machine-driver-vmwareworkstation_windows-%GOARCH%.exe
```

But for the artifact I'm not sure if `%GOARCH%` works here.

For the chocolatey package the name of the exe at the github releases is no problem, the choco installer can rename the plugin to its correct name.

And adding `windows` to the filename there is room for the linux version of this plugin ;-)
